RUN_DIR=/home/vitaly/method-embedding-main/scripts/training
TOKENIZER_PATH=/home/vitaly/data/sentencepiece_bpe.model
DATA_PATH=/home/vitaly/data/v2_subsample_no_spacy_v3/with_ast
PRETRAINED_MODEL_PATH=/home/vitaly/data/v2_subsample_no_spacy_v3/with_ast
EPOCHS=300
EMB_SIZE=300

python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 1 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 2 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 3 --measure_scores --dilate_scores 1 --use_edge_types  --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 4 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 5 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword
#python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 6 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword
#python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 7 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword


python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 1 --measure_scores --dilate_scores 1 --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 2 --measure_scores --dilate_scores 1 --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 3 --measure_scores --dilate_scores 1 --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 4 --measure_scores --dilate_scores 1 --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 5 --measure_scores --dilate_scores 1 --filter_edges subword
#python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 6 --measure_scores --dilate_scores 1 --filter_edges subword
#python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 7 --measure_scores --dilate_scores 1 --filter_edges subword


python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 1 --measure_scores --dilate_scores 1 --use_edge_types
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 2 --measure_scores --dilate_scores 1 --use_edge_types
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 3 --measure_scores --dilate_scores 1 --use_edge_types
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 4 --measure_scores --dilate_scores 1 --use_edge_types
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 5 --measure_scores --dilate_scores 1 --use_edge_types
# python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 6 --measure_scores --dilate_scores 1 --use_edge_types
# python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 7 --measure_scores --dilate_scores 1 --use_edge_types


python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 1 --measure_scores --dilate_scores 1
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 2 --measure_scores --dilate_scores 1
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 3 --measure_scores --dilate_scores 1
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 4 --measure_scores --dilate_scores 1
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 5 --measure_scores --dilate_scores 1
# python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 6 --measure_scores --dilate_scores 1
# python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3  --n_layers 7 --measure_scores --dilate_scores 1


python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 1 --measure_scores --dilate_scores 1
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 2 --measure_scores --dilate_scores 1
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 3 --measure_scores --dilate_scores 1
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 4 --measure_scores --dilate_scores 1
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 5 --measure_scores --dilate_scores 1
# python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 6 --measure_scores --dilate_scores 1
# python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 7 --measure_scores --dilate_scores 1


python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 1 --measure_scores --dilate_scores 1 --use_edge_types
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 2 --measure_scores --dilate_scores 1 --use_edge_types
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 3 --measure_scores --dilate_scores 1 --use_edge_types
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 4 --measure_scores --dilate_scores 1 --use_edge_types
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 5 --measure_scores --dilate_scores 1 --use_edge_types
# python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu -1 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 6 --measure_scores --dilate_scores 1 --use_edge_types
# python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu -1 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 7 --measure_scores --dilate_scores 1 --use_edge_types


python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 1 --measure_scores --dilate_scores 1 --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 2 --measure_scores --dilate_scores 1 --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 3 --measure_scores --dilate_scores 1 --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 4 --measure_scores --dilate_scores 1 --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 5 --measure_scores --dilate_scores 1 --filter_edges subword
#python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 6 --measure_scores --dilate_scores 1 --filter_edges subword
#python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 7 --measure_scores --dilate_scores 1 --filter_edges subword


python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 1 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 2 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 3 --measure_scores --dilate_scores 1 --use_edge_types  --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 4 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword
python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 5 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword
#python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 6 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword
#python $RUN_DIR/train.py --tokenizer $TOKENIZER_PATH --data_path $DATA_PATH --pretraining_phase 0 --epochs $EPOCHS --batch_size 128 $PRETRAINED_MODEL_PATH --gpu 0 --node_emb_size $EMB_SIZE --elem_emb_size $EMB_SIZE --h_dim $EMB_SIZE --train_frac 0.9 --objectives type_ann_pred --min_count_for_objectives 3 --no_global_edges --n_layers 7 --measure_scores --dilate_scores 1 --use_edge_types --filter_edges subword
